name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          path: bot.zip
      - name: Upload Artifiact to production
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          source: "./bot.zip"
          target: "~/bot.zip"
      - name: SSH into production
        id: discord-bot-main-ssh
        uses: appleboy/ssh-action@master
        with: |
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          script: |
            echo "Connected to server!"
            cd ~
            unzip bot.zip
            rm -r /usr/local/opt/SahneeBot-Test/*
            cp -r ./SahneeBot-Linux64/* ${{ secrets.DEPLOY_DIRECTORY }}
            cp ~/appsettings.json ${{ secrets.DEPLOY_DIRECTORY }}
    
