name: .NET

on:
  push:
    tags:
      - '*'
    branches: [ next ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet publish --no-restore --self-contained true --runtime linux-x64 -o output
      - name: Zip
        run: zip -r SahneeBot-Linux64.zip output
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "SahneeBot-Linux64.zip"
          bodyFile: "README.md"
          token: ${{ secrets.GITHUB_TOKEN }}
