name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: [ self-hosted, ubuntu-latest ]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Generate release information
        run: |
          echo "Build Nr: ${{ github.run_number }}" > ./SahneeBot/ReleaseInformation.txt
          echo "Build Timestamp: $(date --rfc-3339=ns)" >>  ./SahneeBot/ReleaseInformation.txt
          echo "Runner: ${{ runner.name }} (${{ runner.os }} ${{ runner.arch }})" >> ./SahneeBot/ReleaseInformation.txt
          echo "Commit: ${{ github.sha }}" >> ./SahneeBot/ReleaseInformation.txt
          echo "Repository: ${{ github.repository }}" >> ./SahneeBot/ReleaseInformation.txt
      - name: Build
        run: dotnet publish --no-restore --self-contained true --runtime linux-x64 -o SahneeBot-Linux64
      - name: Zip
        run: zip -r SahneeBot-Linux64.zip SahneeBot-Linux64
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "SahneeBot-Linux64.zip"
          bodyFile: "README.md"
          tag: ${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}
