name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Generate release information
        run: |
          echo "Build Nr: ${{ github.run_number }}" > ./SahneeBot/ReleaseInformation.txt
          echo "Build Timestamp: $(date --rfc-3339=ns)" >>  ./SahneeBot/ReleaseInformation.txt
          echo "Runner: ${{ runner.name }} (${{ runner.os }} ${{ runner.arch }})" >> ./SahneeBot/ReleaseInformation.txt
          echo "Commit: ${{ github.sha }}" >> ./SahneeBot/ReleaseInformation.txt
          echo "Repository: ${{ github.repository }}" >> ./SahneeBot/ReleaseInformation.txt
      - name: Build
        run: dotnet publish --no-restore --self-contained true --runtime linux-x64 -o SahneeBot-Linux64
      - name: Zip
        run: zip -r SahneeBot-Linux64.zip SahneeBot-Linux64
      - name: Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          path: SahneeBot-Linux64.zip
          if-no-files-found: error
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "SahneeBot-Linux64.zip"
          bodyFile: "README.md"
          tag: ${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          path: bot.zip
      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.2
      - name: Install hcloud
        uses: techknowlogick/action-hcloud@v2
        with:
          version: 1.29.5
          token: ${{ secrets.HCLOUD_TOKEN }}
      - name: Enable project
        run: hcloud context create actions
      - name: Allow IP in Firewall
        run: hcloud firewall add-rule github --source-ips 1.3.5.7/32 --port 22 --protocol tcp --direction in --description "GitHub Actions - sahnee-bot"
      - name: Upload Artifiact to production
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          source: "./bot.zip"
          target: "~/bot.zip"
      - name: SSH into production
        id: discord-bot-main-ssh
        uses: appleboy/ssh-action@master
        with: |
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          script: |
            echo "Connected to server!"
            cd ~
            unzip bot.zip
            rm -r /usr/local/opt/SahneeBot-Test/*
            cp -r ./SahneeBot-Linux64/* ${{ secrets.DEPLOY_DIRECTORY }}
            cp ~/appsettings.json ${{ secrets.DEPLOY_DIRECTORY }}
      - name: Block IP in Firewall
        if: always()
        run: hcloud firewall delete-rule github --source-ips 1.3.5.7/32 --port 22 --protocol tcp --direction in --description "GitHub Actions - sahnee-bot"
